spring.application.name=Advance Opening
server.port= 9090
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=2023200000382@seu.edu.bd
spring.mail.password=ohpv sbhh lybp jlwk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
